### ISSUE TITLE
No recipies found on https://www.scrambledchefs.com/

### ISSUE THREAD

**Issue by RarrellUK** [steven-lm/Jump-To-Recipe#4]
Hi,

I couldn't see any open issues just to let you know the extention says it cannot see recipes on https://www.scrambledchefs.com/

I tried multiple but here is an example recipe I was trying

https://www.scrambledchefs.com/crispy-sticky-thai-chicken-wings/

**Comment by steven-lm** [comment]
Hey Rarrell,

That's strange, all the recipes on that site seem to be working for me. Do you have any other extensions that might affect the page? 

![image](https://user-images.githubusercontent.com/58721655/154774844-cf795b72-6fa1-4610-8eff-c7572330a705.png)
